HAI
	WAZZUP
		I HAS NOW i ITZ 0
		I HAS NOW j ITZ 0
	BUHBYE
	IM IN YR loop1 UPPIN i WILE DIFFRINT i SMALLR OF i AN 5
		i R 0
		IM IN YR loop2 UPPIN j TIL BOTH SAEM j AN 5
			VISIBLE PRODUKT OF i AN j + " " !
		IM OUTTA YR loop2
		VISIBLE ""
	IM OUTTA YR loop1
KTHXBYE
