HAI
	WAZZUP
		I HAS A i ITZ 1
		I HAS A j
	BUHBYE
	IM IN YR loop1 UPPIN YR i WILE DIFFRINT i AN BIGGR OF i AN 10
		j R 1

		IM IN YR loop2 UPPIN YR j TIL BOTH SAEM j AN 10
			VISIBLE PRODUKT OF i AN j + " " !
		IM OUTTA YR loop2

		VISIBLE ""
	IM OUTTA YR loop1
KTHXBYE

